const IMG = {
    noumaCard: new URL('./IMG/00_NOUMA/NOUMA CARTÃO QR R00.png', import.meta.url).href,
    tessSymbol_white: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/tessSymbol_white.png', import.meta.url).href,
    tessSymbol_black: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/tessSymbol_black.png', import.meta.url).href,
    nouma_fullLogo_black: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Preto/Logo Preta.png', import.meta.url).href,
    nouma_onlyName_black: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Preto/Nome Preto.png', import.meta.url).href,
    nouma_lineName_black: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Preto/Nome Horizontal Preto.png', import.meta.url).href,
    nouma_onlySymbol_black: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Preto/Simbolo Preto.png', import.meta.url).href,
    nouma_fullLogo_white: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Branco/Logo Branca.png', import.meta.url).href,
    nouma_onlyName_white: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Branco/Nome Branco.png', import.meta.url).href,
    nouma_lineName_white: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Branco/Nome Horizontal Branco.png', import.meta.url).href,
    nouma_onlySymbol_white: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Branco/Simbolo Branco.png', import.meta.url).href,
    nouma_fullLogo_green: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Verde/Logo verde.png', import.meta.url).href,
    nouma_onlyName_green: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Verde/Nome verde.png', import.meta.url).href,
    nouma_lineName_green: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Verde/Nome Horizontal verde.png', import.meta.url).href,
    nouma_onlySymbol_green: new URL('./IMG/00_NOUMA/Templates Design_R01/Logo/Fundo Transparente/Verde/Simbolo verde.png', import.meta.url).href,

    jumbotron_00: new URL('./IMG/cover/JUMBO_00.webp', import.meta.url).href,
    jumbotron_01: new URL('./IMG/cover/JUMBO_01.webp', import.meta.url).href,
    jumbotron_02: new URL('./IMG/cover/JUMBO_02.webp', import.meta.url).href,
    jumbotron_03: new URL('./IMG/cover/JUMBO_03.webp', import.meta.url).href,
    jumbotron_04: new URL('./IMG/cover/JUMBO_04.webp', import.meta.url).href,
    jumbotron_05: new URL('./IMG/cover/JUMBO_05.webp', import.meta.url).href,
    jumbotron_06: new URL('./IMG/cover/JUMBO_06.webp', import.meta.url).href,
    jumbotron_07: new URL('./IMG/cover/JUMBO_07.webp', import.meta.url).href,
    jumbotron_08: new URL('./IMG/cover/JUMBO_08.webp', import.meta.url).href,
    jumbotron_09: new URL('./IMG/cover/JUMBO_09.webp', import.meta.url).href,
    jumbotron_10: new URL('./IMG/cover/JUMBO_10.webp', import.meta.url).href,
    jumbotron_11: new URL('./IMG/cover/JUMBO_11.webp', import.meta.url).href,
    jumbotron_12: new URL('./IMG/cover/JUMBO_12.webp', import.meta.url).href,
    jumbotron_13: new URL('./IMG/cover/JUMBO_13.webp', import.meta.url).href,
    jumbotron_14: new URL('./IMG/cover/JUMBO_14.webp', import.meta.url).href,
    jumbotron_15: new URL('./IMG/cover/JUMBO_15.webp', import.meta.url).href,
    jumbotron_16: new URL('./IMG/cover/JUMBO_16.webp', import.meta.url).href,
    jumbotron_17: new URL('./IMG/cover/JUMBO_17.webp', import.meta.url).href,
    //jumbotron_18: new URL('./IMG/cover/JUMBO_18.webp', import.meta.url).href,
    //jumbotron_19: new URL('./IMG/cover/JUMBO_19.webp', import.meta.url).href,
    jumbotron_20: new URL('./IMG/cover/JUMBO_20.webp', import.meta.url).href,
    jumbotron_21: new URL('./IMG/cover/JUMBO_21.webp', import.meta.url).href,
    jumbotron_22: new URL('./IMG/cover/JUMBO_22.webp', import.meta.url).href,
    jumbotron_23: new URL('./IMG/cover/JUMBO_23.webp', import.meta.url).href,
    jumbotron_24: new URL('./IMG/cover/JUMBO_24.webp', import.meta.url).href,
    jumbotron_25: new URL('./IMG/cover/JUMBO_25.webp', import.meta.url).href,
    jumbotron_26: new URL('./IMG/cover/JUMBO_26.webp', import.meta.url).href,
    jumbotron_27: new URL('./IMG/cover/JUMBO_27.webp', import.meta.url).href,
    jumbotron_28: new URL('./IMG/cover/JUMBO_28.webp', import.meta.url).href,
    jumbotron_29: new URL('./IMG/cover/JUMBO_29.webp', import.meta.url).href,

    apt404_01: new URL('./IMG/404/select/404_01.webp', import.meta.url).href,
    apt404_02: new URL('./IMG/404/select/404_02.webp', import.meta.url).href,
    apt404_03: new URL('./IMG/404/select/404_03.webp', import.meta.url).href,
    apt404_04: new URL('./IMG/404/select/404_04.webp', import.meta.url).href,
    apt404_05: new URL('./IMG/404/select/404_05.webp', import.meta.url).href,
    apt404_06: new URL('./IMG/404/select/404_06.webp', import.meta.url).href,
    apt404_07: new URL('./IMG/404/select/404_07.webp', import.meta.url).href,
    apt404_08: new URL('./IMG/404/select/404_08.webp', import.meta.url).href,
    apt404_09: new URL('./IMG/404/select/404_09.webp', import.meta.url).href,

    aurora1602_01: new URL('./IMG/AURORA/select/AURORA_01.webp', import.meta.url).href,
    aurora1602_02: new URL('./IMG/AURORA/select/AURORA_04.webp', import.meta.url).href,
    aurora1602_03: new URL('./IMG/AURORA/select/AURORA_05.webp', import.meta.url).href,
    aurora1602_04: new URL('./IMG/AURORA/select/AURORA_08.webp', import.meta.url).href,
    aurora1602_05: new URL('./IMG/AURORA/select/AURORA_17.webp', import.meta.url).href,

    paiva_01: new URL('./IMG/PAIVA/select/PAIVA_DAY_01.webp', import.meta.url).href,
    paiva_02: new URL('./IMG/PAIVA/select/PAIVA_DAY_02.webp', import.meta.url).href,
    paiva_03: new URL('./IMG/PAIVA/select/PAIVA_DAY_03.webp', import.meta.url).href,
    paiva_04: new URL('./IMG/PAIVA/select/PAIVA_DAY_04.webp', import.meta.url).href,
    paiva_05: new URL('./IMG/PAIVA/select/PAIVA_DAY_05.webp', import.meta.url).href,
    paiva_06: new URL('./IMG/PAIVA/select/PAIVA_DAY_06.webp', import.meta.url).href,
    paiva_07: new URL('./IMG/PAIVA/select/PAIVA_DAY_07.webp', import.meta.url).href,
    paiva_08: new URL('./IMG/PAIVA/select/PAIVA_DAY_08.webp', import.meta.url).href,
    paiva_09: new URL('./IMG/PAIVA/select/PAIVA_DAY_09.webp', import.meta.url).href,
    paiva_10: new URL('./IMG/PAIVA/select/PAIVA_DAY_10.webp', import.meta.url).href,
    paiva_11: new URL('./IMG/PAIVA/select/PAIVA_DAY_11.webp', import.meta.url).href,
    paiva_12: new URL('./IMG/PAIVA/select/PAIVA_DAY_12.webp', import.meta.url).href,
    paiva_13: new URL('./IMG/PAIVA/select/PAIVA_DAY_13.webp', import.meta.url).href,
    paiva_14: new URL('./IMG/PAIVA/select/PAIVA_DAY_14.webp', import.meta.url).href,
    paiva_15: new URL('./IMG/PAIVA/select/PAIVA_DAY_15.webp', import.meta.url).href,
    paiva_16: new URL('./IMG/PAIVA/select/PAIVA_DAY_16.webp', import.meta.url).href,
    paiva_17: new URL('./IMG/PAIVA/select/PAIVA_DAY_17.webp', import.meta.url).href,
    paiva_18: new URL('./IMG/PAIVA/select/PAIVA_DAY_18.webp', import.meta.url).href,
    paiva_19: new URL('./IMG/PAIVA/select/PAIVA_DAY_19.webp', import.meta.url).href,
    paiva_20: new URL('./IMG/PAIVA/select/PAIVA_DAY_20.webp', import.meta.url).href,
    paiva_21: new URL('./IMG/PAIVA/select/PAIVA_DAY_21.webp', import.meta.url).href,
    paiva_22: new URL('./IMG/PAIVA/select/PAIVA_DAY_22.webp', import.meta.url).href,
    paiva_photo_01: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_01.webp', import.meta.url).href,
    paiva_photo_02: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_02.webp', import.meta.url).href,
    paiva_photo_03: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_03.webp', import.meta.url).href,
    paiva_photo_04: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_04.webp', import.meta.url).href,
    paiva_photo_05: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_05.webp', import.meta.url).href,
    paiva_photo_06: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_06.webp', import.meta.url).href,
    paiva_photo_07: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_07.webp', import.meta.url).href,
    paiva_photo_08: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_08.webp', import.meta.url).href,
    paiva_photo_09: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_09.webp', import.meta.url).href,
    paiva_photo_10: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_10.webp', import.meta.url).href,
    paiva_photo_11: new URL('./IMG/PAIVA/select/PAIVA_PHOTO_11.webp', import.meta.url).href,

    serrambi_00: new URL('./IMG/SERRAMBI/select/SERRAMBI_00.webp', import.meta.url).href,
    serrambi_01: new URL('./IMG/SERRAMBI/select/SERRAMBI_01.webp', import.meta.url).href,
    serrambi_02: new URL('./IMG/SERRAMBI/select/SERRAMBI_02.webp', import.meta.url).href,
    serrambi_03: new URL('./IMG/SERRAMBI/select/SERRAMBI_03.webp', import.meta.url).href,
    serrambi_04: new URL('./IMG/SERRAMBI/select/SERRAMBI_04.webp', import.meta.url).href,
    serrambi_05: new URL('./IMG/SERRAMBI/select/SERRAMBI_05.webp', import.meta.url).href,
    serrambi_06: new URL('./IMG/SERRAMBI/select/SERRAMBI_06.webp', import.meta.url).href,
    serrambi_07: new URL('./IMG/SERRAMBI/select/SERRAMBI_07.webp', import.meta.url).href,
    serrambi_08: new URL('./IMG/SERRAMBI/select/SERRAMBI_08.webp', import.meta.url).href,
    serrambi_09: new URL('./IMG/SERRAMBI/select/SERRAMBI_09.webp', import.meta.url).href,
    serrambi_10: new URL('./IMG/SERRAMBI/select/SERRAMBI_10.webp', import.meta.url).href,
    serrambi_11: new URL('./IMG/SERRAMBI/select/SERRAMBI_11.webp', import.meta.url).href,
    serrambi_12: new URL('./IMG/SERRAMBI/select/SERRAMBI_12.webp', import.meta.url).href,
    serrambi_13: new URL('./IMG/SERRAMBI/select/SERRAMBI_13.webp', import.meta.url).href,
    serrambi_14: new URL('./IMG/SERRAMBI/select/SERRAMBI_14.webp', import.meta.url).href,
    serrambi_15: new URL('./IMG/SERRAMBI/select/SERRAMBI_15.webp', import.meta.url).href,
    serrambi_16: new URL('./IMG/SERRAMBI/select/SERRAMBI_16.webp', import.meta.url).href,
    serrambi_17: new URL('./IMG/SERRAMBI/select/SERRAMBI_17.webp', import.meta.url).href,
    serrambi_18: new URL('./IMG/SERRAMBI/select/SERRAMBI_18.webp', import.meta.url).href,

    phoneIcon: new URL('./IMG/call.png', import.meta.url).href,
    letterIcon: new URL('./IMG/letter.png', import.meta.url).href,
    placeIcon: new URL('./IMG/maps-and-flags.png', import.meta.url).href,
    menuIcon: new URL('./IMG/menu.png', import.meta.url).href,
    menuYellowIcon: new URL('./IMG/menuYellow.png', import.meta.url).href,
}

export default IMG; 